#![allow(dead_code)]

use crate::backend::compiler::{CompileFlags, Compiler, LinkFlags};
use crate::core::manifest::PackageType;
use serde::Serialize;
use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};

/// Generates build.ninja and compile_commands.json.
///
/// All paths in build.ninja are relative to `build_dir` because ninja runs
/// with `-C build_dir`. The `project_root` is used to compute relative paths
/// from build_dir back to source files and output directory.
pub struct NinjaGenerator<'a> {
    compiler: &'a dyn Compiler,
    sources: Vec<PathBuf>,
    build_dir: PathBuf,
    project_root: PathBuf,
    output_name: String,
    package_type: PackageType,
    compile_flags: CompileFlags,
    link_flags: LinkFlags,
}

#[derive(Debug)]
pub struct NinjaOutput {
    pub build_ninja: String,
    pub compile_commands: String,
}

impl<'a> NinjaGenerator<'a> {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        compiler: &'a dyn Compiler,
        sources: Vec<PathBuf>,
        build_dir: PathBuf,
        project_root: PathBuf,
        output_name: String,
        package_type: PackageType,
        compile_flags: CompileFlags,
        link_flags: LinkFlags,
    ) -> Self {
        Self {
            compiler,
            sources,
            build_dir,
            project_root,
            output_name,
            package_type,
            compile_flags,
            link_flags,
        }
    }

    pub fn generate(&self) -> NinjaOutput {
        let build_ninja = self.generate_ninja();
        let compile_commands = self.generate_compile_commands();
        NinjaOutput {
            build_ninja,
            compile_commands,
        }
    }

    fn rel(&self, path: &Path) -> PathBuf {
        let abs_target = self.project_root.join(path);
        pathdiff::diff_paths(&abs_target, &self.build_dir).unwrap_or(abs_target)
    }

    fn generate_ninja(&self) -> String {
        let mut out = String::new();

        writeln!(out, "# Generated by ordo").unwrap();
        writeln!(out, "ninja_required_version = 1.3").unwrap();
        writeln!(out).unwrap();

        let c_exe = self.compiler.c_executable();
        let cpp_exe = self.compiler.cpp_executable();

        writeln!(out, "rule cc").unwrap();
        writeln!(out, "  command = {c_exe} $flags $in").unwrap();
        writeln!(out, "  depfile = $depfile").unwrap();
        writeln!(out, "  deps = gcc").unwrap();
        writeln!(out, "  description = Compiling $in").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "rule cxx").unwrap();
        writeln!(out, "  command = {cpp_exe} $flags $in").unwrap();
        writeln!(out, "  depfile = $depfile").unwrap();
        writeln!(out, "  deps = gcc").unwrap();
        writeln!(out, "  description = Compiling $in").unwrap();
        writeln!(out).unwrap();

        let link_exe = if self.has_cpp_sources() { cpp_exe } else { c_exe };
        match self.package_type {
            PackageType::Executable => {
                writeln!(out, "rule link").unwrap();
                writeln!(out, "  command = {link_exe} $flags $in -o $out").unwrap();
                writeln!(out, "  description = Linking $out").unwrap();
            }
            PackageType::StaticLibrary => {
                writeln!(out, "rule ar").unwrap();
                writeln!(out, "  command = ar rcs $out $in").unwrap();
                writeln!(out, "  description = Archiving $out").unwrap();
            }
            PackageType::SharedLibrary => {
                writeln!(out, "rule link").unwrap();
                writeln!(out, "  command = {link_exe} -shared $flags $in -o $out").unwrap();
                writeln!(out, "  description = Linking $out").unwrap();
            }
        }
        writeln!(out).unwrap();

        // Build statements — all paths relative to build_dir
        let mut objects = Vec::new();
        for src in &self.sources {
            let rel_src = self.rel(src);
            let stem = src.file_stem().unwrap_or_default().to_string_lossy();
            let obj = format!("{stem}.o");
            let depfile = format!("{stem}.d");

            let compile_flags = self.compile_flags_str();
            let rule = if is_cpp_source(src) { "cxx" } else { "cc" };

            writeln!(out, "build {obj}: {rule} {}", rel_src.display()).unwrap();
            writeln!(out, "  depfile = {depfile}").unwrap();
            writeln!(out, "  flags = {compile_flags}").unwrap();
            writeln!(out).unwrap();

            objects.push(obj);
        }

        // Output path relative to build_dir
        let rel_output = self.rel_output();
        let objs_str = objects.join(" ");

        match self.package_type {
            PackageType::Executable | PackageType::SharedLibrary => {
                let lflags = self.link_flags_str();
                writeln!(out, "build {}: link {objs_str}", rel_output.display()).unwrap();
                if !lflags.is_empty() {
                    writeln!(out, "  flags = {lflags}").unwrap();
                }
            }
            PackageType::StaticLibrary => {
                writeln!(out, "build {}: ar {objs_str}", rel_output.display()).unwrap();
            }
        }
        writeln!(out).unwrap();

        writeln!(out, "default {}", rel_output.display()).unwrap();

        out
    }

    fn compile_flags_str(&self) -> String {
        let mut flags = vec!["-c".to_string()];

        if let Some(std) = self.compile_flags.cpp_standard {
            flags.push(format!("-std={}", std.as_flag()));
        } else if let Some(std) = self.compile_flags.c_standard {
            flags.push(format!("-std={}", std.as_flag()));
        }

        flags.push(format!("-O{}", self.compile_flags.opt_level));

        if self.compile_flags.debug {
            flags.push("-g".to_string());
        }

        for def in &self.compile_flags.defines {
            flags.push(format!("-D{def}"));
        }

        for inc in &self.compile_flags.include_dirs {
            let rel_inc = self.rel(inc);
            flags.push(format!("-I{}", rel_inc.display()));
        }

        flags.push("-MD".to_string());
        flags.push("-MF".to_string());
        flags.push("$depfile".to_string());

        flags.push("-o".to_string());
        flags.push("$out".to_string());

        flags.join(" ")
    }

    fn link_flags_str(&self) -> String {
        let mut flags = Vec::new();
        if let Some(linker) = self.link_flags.linker {
            flags.push(format!("-fuse-ld={linker}"));
        }
        for dir in &self.link_flags.lib_dirs {
            flags.push(format!("-L{}", dir.display()));
        }
        for lib in &self.link_flags.libs {
            flags.push(format!("-l{lib}"));
        }
        for fw in &self.link_flags.frameworks {
            flags.push("-framework".to_string());
            flags.push(fw.clone());
        }
        flags.join(" ")
    }

    fn has_cpp_sources(&self) -> bool {
        self.sources.iter().any(|s| is_cpp_source(s))
    }

    fn rel_output(&self) -> PathBuf {
        let output_dir = self.build_dir.parent().unwrap_or(Path::new("."));
        let output = match self.package_type {
            PackageType::Executable => output_dir.join(&self.output_name),
            PackageType::StaticLibrary => output_dir.join(format!("lib{}.a", self.output_name)),
            PackageType::SharedLibrary => output_dir.join(format!("lib{}.so", self.output_name)),
        };
        self.rel(&output)
    }

    fn generate_compile_commands(&self) -> String {
        let project_root = &self.project_root;
        let entries: Vec<CompileCommandEntry> = self
            .sources
            .iter()
            .map(|src| {
                let abs_src = project_root.join(src);
                let obj = PathBuf::from(format!(
                    "{}.o",
                    src.file_stem().unwrap_or_default().to_string_lossy()
                ));
                let depfile = obj.with_extension("d");
                let args = self.compiler.compile_args(&abs_src, &obj, &depfile, &self.compile_flags);
                let exe = if is_cpp_source(src) {
                    self.compiler.cpp_executable()
                } else {
                    self.compiler.c_executable()
                };
                let mut command = vec![exe.to_string()];
                command.extend(args);

                CompileCommandEntry {
                    directory: project_root.display().to_string(),
                    file: src.display().to_string(),
                    arguments: command,
                }
            })
            .collect();

        serde_json::to_string_pretty(&entries).unwrap_or_else(|_| "[]".to_string())
    }
}

fn is_cpp_source(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|e| e.to_str()),
        Some("cpp" | "cc" | "cxx" | "C")
    )
}

#[derive(Serialize)]
struct CompileCommandEntry {
    directory: String,
    file: String,
    arguments: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::compiler::clang::ClangCompiler;

    fn basic_generator(package_type: PackageType) -> NinjaOutput {
        let compiler = ClangCompiler;
        let sources = vec![PathBuf::from("src/main.cpp")];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            PathBuf::from("."),
            "myapp".to_string(),
            package_type,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        generator.generate()
    }

    #[test]
    fn ninja_has_required_version() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("ninja_required_version"));
    }

    #[test]
    fn ninja_has_compile_rule() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("rule cc"));
        assert!(output.build_ninja.contains("depfile"));
    }

    #[test]
    fn ninja_executable_has_link_rule() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("rule link"));
        assert!(output.build_ninja.contains("myapp"));
    }

    #[test]
    fn ninja_static_library_has_ar_rule() {
        let output = basic_generator(PackageType::StaticLibrary);
        assert!(output.build_ninja.contains("rule ar"));
        assert!(output.build_ninja.contains("libmyapp.a"));
    }

    #[test]
    fn ninja_shared_library_has_shared_flag() {
        let output = basic_generator(PackageType::SharedLibrary);
        assert!(output.build_ninja.contains("-shared"));
        assert!(output.build_ninja.contains("libmyapp.so"));
    }

    #[test]
    fn ninja_has_default_target() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("default"));
        assert!(output.build_ninja.contains("myapp"));
    }

    #[test]
    fn ninja_multiple_sources() {
        let compiler = ClangCompiler;
        let sources = vec![
            PathBuf::from("src/main.cpp"),
            PathBuf::from("src/util.cpp"),
        ];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            PathBuf::from("."),
            "myapp".to_string(),
            PackageType::Executable,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        let output = generator.generate();

        assert!(output.build_ninja.contains("build main.o: cxx"));
        assert!(output.build_ninja.contains("build util.o: cxx"));
    }

    #[test]
    fn compile_commands_is_valid_json() {
        let output = basic_generator(PackageType::Executable);
        let parsed: Vec<serde_json::Value> =
            serde_json::from_str(&output.compile_commands).unwrap();
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0]["file"], "src/main.cpp");
        assert!(parsed[0]["arguments"].as_array().unwrap().len() > 1);
    }

    #[test]
    fn compile_commands_multiple_sources() {
        let compiler = ClangCompiler;
        let sources = vec![
            PathBuf::from("src/main.cpp"),
            PathBuf::from("src/util.cpp"),
        ];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            PathBuf::from("."),
            "myapp".to_string(),
            PackageType::Executable,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        let output = generator.generate();

        let parsed: Vec<serde_json::Value> =
            serde_json::from_str(&output.compile_commands).unwrap();
        assert_eq!(parsed.len(), 2);
    }
}
