#![allow(dead_code)]

use crate::backend::compiler::{CompileFlags, Compiler, LinkFlags};
use crate::core::manifest::PackageType;
use serde::Serialize;
use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};

pub struct NinjaGenerator<'a> {
    compiler: &'a dyn Compiler,
    sources: Vec<PathBuf>,
    build_dir: PathBuf,
    output_name: String,
    package_type: PackageType,
    compile_flags: CompileFlags,
    link_flags: LinkFlags,
}

#[derive(Debug)]
pub struct NinjaOutput {
    pub build_ninja: String,
    pub compile_commands: String,
}

impl<'a> NinjaGenerator<'a> {
    pub fn new(
        compiler: &'a dyn Compiler,
        sources: Vec<PathBuf>,
        build_dir: PathBuf,
        output_name: String,
        package_type: PackageType,
        compile_flags: CompileFlags,
        link_flags: LinkFlags,
    ) -> Self {
        Self {
            compiler,
            sources,
            build_dir,
            output_name,
            package_type,
            compile_flags,
            link_flags,
        }
    }

    pub fn generate(&self) -> NinjaOutput {
        let build_ninja = self.generate_ninja();
        let compile_commands = self.generate_compile_commands();
        NinjaOutput {
            build_ninja,
            compile_commands,
        }
    }

    fn generate_ninja(&self) -> String {
        let mut out = String::new();

        // Header
        writeln!(out, "# Generated by ordo").unwrap();
        writeln!(out, "ninja_required_version = 1.3").unwrap();
        writeln!(out).unwrap();

        // Compile rule
        let exe = self.compiler.executable();
        writeln!(out, "rule cc").unwrap();
        writeln!(out, "  command = {exe} $flags $in").unwrap();
        writeln!(out, "  depfile = $depfile").unwrap();
        writeln!(out, "  deps = gcc").unwrap();
        writeln!(out, "  description = Compiling $in").unwrap();
        writeln!(out).unwrap();

        // Link rule
        match self.package_type {
            PackageType::Executable => {
                writeln!(out, "rule link").unwrap();
                writeln!(out, "  command = {exe} $flags $in -o $out").unwrap();
                writeln!(out, "  description = Linking $out").unwrap();
            }
            PackageType::StaticLibrary => {
                writeln!(out, "rule ar").unwrap();
                writeln!(out, "  command = ar rcs $out $in").unwrap();
                writeln!(out, "  description = Archiving $out").unwrap();
            }
            PackageType::SharedLibrary => {
                writeln!(out, "rule link").unwrap();
                writeln!(out, "  command = {exe} -shared $flags $in -o $out").unwrap();
                writeln!(out, "  description = Linking $out").unwrap();
            }
        }
        writeln!(out).unwrap();

        // Build statements
        let mut objects = Vec::new();
        for src in &self.sources {
            let obj = self.object_path(src);
            let depfile = obj.with_extension("d");

            let dummy_depfile_path = Path::new("dummy.d");
            let compile_args = self.compiler.compile_args(
                src,
                &obj,
                dummy_depfile_path,
                &self.compile_flags,
            );
            // Remove src, -o obj, -MF dummy.d from args to get just flags
            let flags = compile_args
                .iter()
                .filter(|a| {
                    *a != &src.display().to_string()
                        && *a != &obj.display().to_string()
                        && *a != "dummy.d"
                        && *a != "-MF"
                        && *a != "-o"
                })
                .cloned()
                .collect::<Vec<_>>()
                .join(" ");

            writeln!(out, "build {}: cc {}", obj.display(), src.display()).unwrap();
            writeln!(out, "  depfile = {}", depfile.display()).unwrap();
            writeln!(out, "  flags = {flags}").unwrap();
            writeln!(out).unwrap();

            objects.push(obj);
        }

        // Final link/archive
        let output = self.output_path();
        let objs_str: Vec<String> = objects.iter().map(|o| o.display().to_string()).collect();

        match self.package_type {
            PackageType::Executable | PackageType::SharedLibrary => {
                let link_args = self.compiler.link_args(&objects, &output, &self.link_flags);
                let link_flags = link_args
                    .iter()
                    .filter(|a| {
                        !objects.iter().any(|o| a.as_str() == o.display().to_string())
                            && *a != "-o"
                            && *a != &output.display().to_string()
                    })
                    .cloned()
                    .collect::<Vec<_>>()
                    .join(" ");

                let rule = match self.package_type {
                    PackageType::SharedLibrary => "link",
                    _ => "link",
                };
                writeln!(out, "build {}: {rule} {}", output.display(), objs_str.join(" ")).unwrap();
                if !link_flags.is_empty() {
                    writeln!(out, "  flags = {link_flags}").unwrap();
                }
            }
            PackageType::StaticLibrary => {
                writeln!(out, "build {}: ar {}", output.display(), objs_str.join(" ")).unwrap();
            }
        }
        writeln!(out).unwrap();

        writeln!(out, "default {}", output.display()).unwrap();

        out
    }

    fn generate_compile_commands(&self) -> String {
        let entries: Vec<CompileCommandEntry> = self
            .sources
            .iter()
            .map(|src| {
                let obj = self.object_path(src);
                let depfile = obj.with_extension("d");
                let args = self.compiler.compile_args(src, &obj, &depfile, &self.compile_flags);
                let mut command = vec![self.compiler.executable().to_string()];
                command.extend(args);

                CompileCommandEntry {
                    directory: std::env::current_dir()
                        .unwrap_or_default()
                        .display()
                        .to_string(),
                    file: src.display().to_string(),
                    arguments: command,
                }
            })
            .collect();

        serde_json::to_string_pretty(&entries).unwrap_or_else(|_| "[]".to_string())
    }

    fn object_path(&self, src: &Path) -> PathBuf {
        let stem = src
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        self.build_dir.join(format!("{stem}.o"))
    }

    fn output_path(&self) -> PathBuf {
        let parent = self.build_dir.parent().unwrap_or(Path::new("."));
        match self.package_type {
            PackageType::Executable => parent.join(&self.output_name),
            PackageType::StaticLibrary => parent.join(format!("lib{}.a", self.output_name)),
            PackageType::SharedLibrary => parent.join(format!("lib{}.so", self.output_name)),
        }
    }
}

#[derive(Serialize)]
struct CompileCommandEntry {
    directory: String,
    file: String,
    arguments: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::compiler::clang::ClangCompiler;

    fn basic_generator(package_type: PackageType) -> NinjaOutput {
        let compiler = ClangCompiler;
        let sources = vec![PathBuf::from("src/main.cpp")];
        let build_dir = PathBuf::from("target/debug/build");
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            build_dir,
            "myapp".to_string(),
            package_type,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        generator.generate()
    }

    #[test]
    fn ninja_has_required_version() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("ninja_required_version"));
    }

    #[test]
    fn ninja_has_compile_rule() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("rule cc"));
        assert!(output.build_ninja.contains("depfile"));
    }

    #[test]
    fn ninja_executable_has_link_rule() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("rule link"));
        assert!(output.build_ninja.contains("target/debug/myapp"));
    }

    #[test]
    fn ninja_static_library_has_ar_rule() {
        let output = basic_generator(PackageType::StaticLibrary);
        assert!(output.build_ninja.contains("rule ar"));
        assert!(output.build_ninja.contains("libmyapp.a"));
    }

    #[test]
    fn ninja_shared_library_has_shared_flag() {
        let output = basic_generator(PackageType::SharedLibrary);
        assert!(output.build_ninja.contains("-shared"));
        assert!(output.build_ninja.contains("libmyapp.so"));
    }

    #[test]
    fn ninja_has_default_target() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("default target/debug/myapp"));
    }

    #[test]
    fn ninja_multiple_sources() {
        let compiler = ClangCompiler;
        let sources = vec![
            PathBuf::from("src/main.cpp"),
            PathBuf::from("src/util.cpp"),
        ];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            "myapp".to_string(),
            PackageType::Executable,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        let output = generator.generate();

        assert!(output.build_ninja.contains("build target/debug/build/main.o: cc src/main.cpp"));
        assert!(output.build_ninja.contains("build target/debug/build/util.o: cc src/util.cpp"));
        assert!(output.build_ninja.contains("main.o") && output.build_ninja.contains("util.o"));
    }

    #[test]
    fn compile_commands_is_valid_json() {
        let output = basic_generator(PackageType::Executable);
        let parsed: Vec<serde_json::Value> =
            serde_json::from_str(&output.compile_commands).unwrap();
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0]["file"], "src/main.cpp");
        assert!(parsed[0]["arguments"].as_array().unwrap().len() > 1);
    }

    #[test]
    fn compile_commands_multiple_sources() {
        let compiler = ClangCompiler;
        let sources = vec![
            PathBuf::from("src/main.cpp"),
            PathBuf::from("src/util.cpp"),
        ];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            "myapp".to_string(),
            PackageType::Executable,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        let output = generator.generate();

        let parsed: Vec<serde_json::Value> =
            serde_json::from_str(&output.compile_commands).unwrap();
        assert_eq!(parsed.len(), 2);
    }
}
