#![allow(dead_code)]

use crate::compiler::{CompileFlags, Compiler, LinkFlags};
use ordo_core::manifest::PackageType;
use serde::Serialize;
use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};

/// Generates build.ninja and compile_commands.json.
///
/// All paths in build.ninja are relative to `build_dir` because ninja runs
/// with `-C build_dir`. The `project_root` is used to compute relative paths
/// from build_dir back to source files and output directory.
pub struct NinjaGenerator<'a> {
    compiler: &'a dyn Compiler,
    sources: Vec<PathBuf>,
    build_dir: PathBuf,
    project_root: PathBuf,
    output_name: String,
    package_type: PackageType,
    compile_flags: CompileFlags,
    link_flags: LinkFlags,
    system_include_dirs: Vec<PathBuf>,
}

#[derive(Debug)]
pub struct NinjaOutput {
    pub build_ninja: String,
    pub compile_commands: String,
}

impl<'a> NinjaGenerator<'a> {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        compiler: &'a dyn Compiler,
        sources: Vec<PathBuf>,
        build_dir: PathBuf,
        project_root: PathBuf,
        output_name: String,
        package_type: PackageType,
        compile_flags: CompileFlags,
        link_flags: LinkFlags,
    ) -> Self {
        let system_include_dirs =
            crate::backend::compiler::query_system_includes(compiler.cpp_executable());
        Self {
            compiler,
            sources,
            build_dir,
            project_root,
            output_name,
            package_type,
            compile_flags,
            link_flags,
            system_include_dirs,
        }
    }

    pub fn generate(&self) -> NinjaOutput {
        let build_ninja = self.generate_ninja();
        let compile_commands = self.generate_compile_commands();
        NinjaOutput {
            build_ninja,
            compile_commands,
        }
    }

    fn rel(&self, path: &Path) -> PathBuf {
        let abs_target = self.project_root.join(path);
        pathdiff::diff_paths(&abs_target, &self.build_dir).unwrap_or(abs_target)
    }

    fn generate_ninja(&self) -> String {
        let mut out = String::new();
        let msvc = self.compiler.is_msvc();

        writeln!(out, "# Generated by ordo").unwrap();
        writeln!(out, "ninja_required_version = 1.3").unwrap();
        writeln!(out).unwrap();

        let c_exe = self.compiler.c_executable();
        let cpp_exe = self.compiler.cpp_executable();

        if msvc {
            writeln!(out, "rule cc").unwrap();
            writeln!(
                out,
                "  command = {c_exe} /nologo $flags /showIncludes /Fo$out $in"
            )
            .unwrap();
            writeln!(out, "  deps = msvc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();

            writeln!(out, "rule cxx").unwrap();
            writeln!(
                out,
                "  command = {cpp_exe} /nologo $flags /showIncludes /Fo$out $in"
            )
            .unwrap();
            writeln!(out, "  deps = msvc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();
        } else {
            writeln!(out, "rule cc").unwrap();
            writeln!(out, "  command = {c_exe} $flags -MD -MF $out.d -o $out $in").unwrap();
            writeln!(out, "  depfile = $out.d").unwrap();
            writeln!(out, "  deps = gcc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();

            writeln!(out, "rule cxx").unwrap();
            writeln!(
                out,
                "  command = {cpp_exe} $flags -MD -MF $out.d -o $out $in"
            )
            .unwrap();
            writeln!(out, "  depfile = $out.d").unwrap();
            writeln!(out, "  deps = gcc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();
        }

        if msvc {
            match self.package_type {
                PackageType::Executable => {
                    writeln!(out, "rule link").unwrap();
                    writeln!(out, "  command = link.exe /nologo $flags $in /OUT:$out").unwrap();
                    writeln!(out, "  description = Linking $out").unwrap();
                }
                PackageType::StaticLibrary => {
                    writeln!(out, "rule ar").unwrap();
                    writeln!(out, "  command = lib.exe /nologo /OUT:$out $in").unwrap();
                    writeln!(out, "  description = Archiving $out").unwrap();
                }
                PackageType::SharedLibrary => {
                    writeln!(out, "rule link").unwrap();
                    writeln!(
                        out,
                        "  command = link.exe /nologo /DLL $flags $in /OUT:$out"
                    )
                    .unwrap();
                    writeln!(out, "  description = Linking $out").unwrap();
                }
            }
        } else {
            let link_exe = if self.has_cpp_sources() {
                cpp_exe
            } else {
                c_exe
            };
            match self.package_type {
                PackageType::Executable => {
                    writeln!(out, "rule link").unwrap();
                    writeln!(out, "  command = {link_exe} $flags $in -o $out").unwrap();
                    writeln!(out, "  description = Linking $out").unwrap();
                }
                PackageType::StaticLibrary => {
                    writeln!(out, "rule ar").unwrap();
                    writeln!(out, "  command = ar rcs $out $in").unwrap();
                    writeln!(out, "  description = Archiving $out").unwrap();
                }
                PackageType::SharedLibrary => {
                    writeln!(out, "rule link").unwrap();
                    writeln!(out, "  command = {link_exe} -shared $flags $in -o $out").unwrap();
                    writeln!(out, "  description = Linking $out").unwrap();
                }
            }
        }
        writeln!(out).unwrap();

        let obj_ext = if msvc { "obj" } else { "o" };

        // Build statements — all paths relative to build_dir
        let mut objects = Vec::new();
        for src in &self.sources {
            let rel_src = self.rel(src);
            let stem = src.file_stem().unwrap_or_default().to_string_lossy();
            let obj = format!("{stem}.{obj_ext}");

            let cpp = is_cpp_source(src);
            let compile_flags = self.compile_flags_str_for(cpp);
            let rule = if cpp { "cxx" } else { "cc" };

            writeln!(out, "build {obj}: {rule} {}", rel_src.display()).unwrap();
            writeln!(out, "  flags = {compile_flags}").unwrap();
            writeln!(out).unwrap();

            objects.push(obj);
        }

        // Output path relative to build_dir
        let rel_output = self.rel_output();
        let objs_str = objects.join(" ");

        match self.package_type {
            PackageType::Executable | PackageType::SharedLibrary => {
                let lflags = self.link_flags_str();
                writeln!(out, "build {}: link {objs_str}", rel_output.display()).unwrap();
                if !lflags.is_empty() {
                    writeln!(out, "  flags = {lflags}").unwrap();
                }
            }
            PackageType::StaticLibrary => {
                writeln!(out, "build {}: ar {objs_str}", rel_output.display()).unwrap();
            }
        }
        writeln!(out).unwrap();

        writeln!(out, "default {}", rel_output.display()).unwrap();

        out
    }

    fn compile_flags_str_for(&self, cpp: bool) -> String {
        if self.compiler.is_msvc() {
            return self.msvc_compile_flags_str_for(cpp);
        }

        let mut flags = vec!["-c".to_string()];

        if cpp {
            if let Some(std) = self.compile_flags.cpp_standard {
                flags.push(format!("-std={}", std.as_flag()));
            }
        } else if let Some(std) = self.compile_flags.c_standard {
            flags.push(format!("-std={}", std.as_flag()));
        }

        flags.push(format!("-O{}", self.compile_flags.opt_level.as_flag()));

        if self.compile_flags.debug {
            flags.push("-g".to_string());
        }

        for def in &self.compile_flags.defines {
            flags.push(format!("-D{def}"));
        }

        for inc in &self.compile_flags.include_dirs {
            let rel_inc = self.rel(inc);
            flags.push(format!("-I{}", rel_inc.display()));
        }

        flags.join(" ")
    }

    fn msvc_compile_flags_str_for(&self, cpp: bool) -> String {
        use ordo_core::manifest::{CppStandard, OptLevel, WarningLevel};

        let mut flags = vec!["/c".to_string()];

        if cpp && let Some(std) = self.compile_flags.cpp_standard {
            let flag = match std {
                CppStandard::Cpp17 => "/std:c++17",
                CppStandard::Cpp20 => "/std:c++20",
                CppStandard::Cpp23 | CppStandard::Cpp26 => "/std:c++latest",
            };
            flags.push(flag.to_string());
        }

        match self.compile_flags.opt_level {
            OptLevel::O0 => flags.push("/Od".to_string()),
            OptLevel::O1 | OptLevel::Os | OptLevel::Oz => flags.push("/O1".to_string()),
            OptLevel::O2 | OptLevel::O3 => flags.push("/O2".to_string()),
        }

        if self.compile_flags.debug {
            flags.push("/Zi".to_string());
        }

        if !self.compile_flags.assertions {
            flags.push("/DNDEBUG".to_string());
        }

        if cpp && self.compile_flags.cpp_standard.is_some() {
            if !self.compile_flags.rtti {
                flags.push("/GR-".to_string());
            }
            if self.compile_flags.exceptions {
                flags.push("/EHsc".to_string());
            }
        }

        match self.compile_flags.warnings {
            WarningLevel::Default => flags.push("/W3".to_string()),
            WarningLevel::All => flags.push("/W4".to_string()),
            WarningLevel::Extra => flags.push("/Wall".to_string()),
            WarningLevel::Error => {
                flags.push("/W4".to_string());
                flags.push("/WX".to_string());
            }
        }

        for def in &self.compile_flags.defines {
            flags.push(format!("/D{def}"));
        }

        for inc in &self.compile_flags.include_dirs {
            let rel_inc = self.rel(inc);
            flags.push(format!("/I{}", rel_inc.display()));
        }

        flags.join(" ")
    }

    fn link_flags_str(&self) -> String {
        if self.compiler.is_msvc() {
            return self.msvc_link_flags_str();
        }

        let mut flags = Vec::new();
        if let Some(linker) = self.link_flags.linker {
            flags.push(format!("-fuse-ld={linker}"));
        }
        for dir in &self.link_flags.lib_dirs {
            flags.push(format!("-L{}", dir.display()));
        }
        for lib in &self.link_flags.libs {
            flags.push(format!("-l{lib}"));
        }
        for fw in &self.link_flags.frameworks {
            flags.push("-framework".to_string());
            flags.push(fw.clone());
        }
        flags.join(" ")
    }

    fn msvc_link_flags_str(&self) -> String {
        use ordo_core::manifest::LtoMode;

        let mut flags = Vec::new();
        match self.link_flags.lto {
            LtoMode::Off => {}
            LtoMode::Thin | LtoMode::Full => flags.push("/LTCG".to_string()),
        }
        if self.link_flags.strip {
            flags.push("/DEBUG:NONE".to_string());
        }
        for dir in &self.link_flags.lib_dirs {
            flags.push(format!("/LIBPATH:{}", dir.display()));
        }
        for lib in &self.link_flags.libs {
            flags.push(format!("{lib}.lib"));
        }
        flags.join(" ")
    }

    fn compile_flags_for(&self, cpp: bool) -> CompileFlags {
        let mut flags = self.compile_flags.clone();
        if cpp {
            flags.c_standard = None;
        } else {
            flags.cpp_standard = None;
        }
        flags
    }

    fn has_cpp_sources(&self) -> bool {
        self.sources.iter().any(|s| is_cpp_source(s))
    }

    fn rel_output(&self) -> PathBuf {
        use crate::compiler::{
            executable_extension, shared_lib_extension, static_lib_extension, static_lib_prefix,
        };

        let output_dir = self.build_dir.parent().unwrap_or(Path::new("."));
        let output = match self.package_type {
            PackageType::Executable => {
                output_dir.join(format!("{}{}", self.output_name, executable_extension()))
            }
            PackageType::StaticLibrary => output_dir.join(format!(
                "{}{}{}",
                static_lib_prefix(),
                self.output_name,
                static_lib_extension()
            )),
            PackageType::SharedLibrary => output_dir.join(format!(
                "{}{}{}",
                static_lib_prefix(),
                self.output_name,
                shared_lib_extension()
            )),
        };
        self.rel(&output)
    }

    fn generate_compile_commands(&self) -> String {
        let project_root = &self.project_root;
        let entries: Vec<CompileCommandEntry> = self
            .sources
            .iter()
            .map(|src| {
                let abs_src = project_root.join(src);
                let obj = PathBuf::from(format!(
                    "{}.o",
                    src.file_stem().unwrap_or_default().to_string_lossy()
                ));
                let depfile = obj.with_extension("d");
                let cpp = is_cpp_source(src);
                let flags = self.compile_flags_for(cpp);
                let args = self.compiler.compile_args(&abs_src, &obj, &depfile, &flags);
                let exe = if cpp {
                    self.compiler.cpp_executable()
                } else {
                    self.compiler.c_executable()
                };
                let mut command = vec![exe.to_string()];
                command.extend(args);
                for sys_inc in &self.system_include_dirs {
                    command.push("-isystem".to_string());
                    command.push(sys_inc.display().to_string());
                }

                CompileCommandEntry {
                    directory: project_root.display().to_string(),
                    file: src.display().to_string(),
                    arguments: command,
                }
            })
            .collect();

        serde_json::to_string_pretty(&entries).unwrap_or_else(|_| "[]".to_string())
    }
}

fn is_cpp_source(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|e| e.to_str()),
        Some("cpp" | "cc" | "cxx" | "C")
    )
}

#[derive(Serialize)]
struct CompileCommandEntry {
    directory: String,
    file: String,
    arguments: Vec<String>,
}

pub struct TestBinarySpec {
    pub name: String,
    pub test_source: PathBuf,
    pub framework_libs: Vec<String>,
    pub framework_lib_dirs: Vec<PathBuf>,
    pub framework_include_dirs: Vec<PathBuf>,
}

pub struct TestNinjaGenerator<'a> {
    compiler: &'a dyn Compiler,
    build_dir: PathBuf,
    project_root: PathBuf,
    compile_flags: CompileFlags,
    link_flags: LinkFlags,
    lib_sources: Vec<PathBuf>,
    lib_name: Option<String>,
    project_lib_path: Option<PathBuf>,
    tests: Vec<TestBinarySpec>,
}

pub struct TestNinjaOutput {
    pub build_ninja: String,
    pub test_binaries: Vec<(String, PathBuf)>,
}

impl<'a> TestNinjaGenerator<'a> {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        compiler: &'a dyn Compiler,
        build_dir: PathBuf,
        project_root: PathBuf,
        compile_flags: CompileFlags,
        link_flags: LinkFlags,
        lib_sources: Vec<PathBuf>,
        lib_name: Option<String>,
        project_lib_path: Option<PathBuf>,
        tests: Vec<TestBinarySpec>,
    ) -> Self {
        Self {
            compiler,
            build_dir,
            project_root,
            compile_flags,
            link_flags,
            lib_sources,
            lib_name,
            project_lib_path,
            tests,
        }
    }

    fn rel(&self, path: &Path) -> PathBuf {
        let abs_target = self.project_root.join(path);
        pathdiff::diff_paths(&abs_target, &self.build_dir).unwrap_or(abs_target)
    }

    fn compile_flags_str_for(&self, cpp: bool, extra_include_dirs: &[PathBuf]) -> String {
        if self.compiler.is_msvc() {
            return self.msvc_compile_flags_str_for(cpp, extra_include_dirs);
        }

        let mut flags = vec!["-c".to_string()];

        if cpp {
            if let Some(std) = self.compile_flags.cpp_standard {
                flags.push(format!("-std={}", std.as_flag()));
            }
        } else if let Some(std) = self.compile_flags.c_standard {
            flags.push(format!("-std={}", std.as_flag()));
        }

        flags.push(format!("-O{}", self.compile_flags.opt_level.as_flag()));

        if self.compile_flags.debug {
            flags.push("-g".to_string());
        }

        for def in &self.compile_flags.defines {
            flags.push(format!("-D{def}"));
        }

        for inc in &self.compile_flags.include_dirs {
            let rel_inc = self.rel(inc);
            flags.push(format!("-I{}", rel_inc.display()));
        }

        for inc in extra_include_dirs {
            let rel_inc = self.rel(inc);
            flags.push(format!("-I{}", rel_inc.display()));
        }

        flags.join(" ")
    }

    fn msvc_compile_flags_str_for(&self, cpp: bool, extra_include_dirs: &[PathBuf]) -> String {
        use ordo_core::manifest::{CppStandard, OptLevel, WarningLevel};

        let mut flags = vec!["/c".to_string()];

        if cpp && let Some(std) = self.compile_flags.cpp_standard {
            let flag = match std {
                CppStandard::Cpp17 => "/std:c++17",
                CppStandard::Cpp20 => "/std:c++20",
                CppStandard::Cpp23 | CppStandard::Cpp26 => "/std:c++latest",
            };
            flags.push(flag.to_string());
        }

        match self.compile_flags.opt_level {
            OptLevel::O0 => flags.push("/Od".to_string()),
            OptLevel::O1 | OptLevel::Os | OptLevel::Oz => flags.push("/O1".to_string()),
            OptLevel::O2 | OptLevel::O3 => flags.push("/O2".to_string()),
        }

        if self.compile_flags.debug {
            flags.push("/Zi".to_string());
        }

        if !self.compile_flags.assertions {
            flags.push("/DNDEBUG".to_string());
        }

        match self.compile_flags.warnings {
            WarningLevel::Default => flags.push("/W3".to_string()),
            WarningLevel::All => flags.push("/W4".to_string()),
            WarningLevel::Extra => flags.push("/Wall".to_string()),
            WarningLevel::Error => {
                flags.push("/W4".to_string());
                flags.push("/WX".to_string());
            }
        }

        for def in &self.compile_flags.defines {
            flags.push(format!("/D{def}"));
        }

        for inc in &self.compile_flags.include_dirs {
            let rel_inc = self.rel(inc);
            flags.push(format!("/I{}", rel_inc.display()));
        }

        for inc in extra_include_dirs {
            let rel_inc = self.rel(inc);
            flags.push(format!("/I{}", rel_inc.display()));
        }

        flags.join(" ")
    }

    fn link_flags_str(&self, extra_lib_dirs: &[PathBuf], extra_libs: &[String]) -> String {
        if self.compiler.is_msvc() {
            return self.msvc_link_flags_str(extra_lib_dirs, extra_libs);
        }

        let mut flags = Vec::new();
        if let Some(linker) = self.link_flags.linker {
            flags.push(format!("-fuse-ld={linker}"));
        }
        for dir in &self.link_flags.lib_dirs {
            flags.push(format!("-L{}", dir.display()));
        }
        for dir in extra_lib_dirs {
            flags.push(format!("-L{}", dir.display()));
        }
        for lib in &self.link_flags.libs {
            flags.push(format!("-l{lib}"));
        }
        for lib in extra_libs {
            flags.push(format!("-l{lib}"));
        }
        for fw in &self.link_flags.frameworks {
            flags.push("-framework".to_string());
            flags.push(fw.clone());
        }
        flags.join(" ")
    }

    fn msvc_link_flags_str(&self, extra_lib_dirs: &[PathBuf], extra_libs: &[String]) -> String {
        let mut flags = Vec::new();
        for dir in &self.link_flags.lib_dirs {
            flags.push(format!("/LIBPATH:{}", dir.display()));
        }
        for dir in extra_lib_dirs {
            flags.push(format!("/LIBPATH:{}", dir.display()));
        }
        for lib in &self.link_flags.libs {
            flags.push(format!("{lib}.lib"));
        }
        for lib in extra_libs {
            flags.push(format!("{lib}.lib"));
        }
        flags.join(" ")
    }

    pub fn generate(&self) -> TestNinjaOutput {
        let mut out = String::new();
        let mut test_binaries = Vec::new();
        let msvc = self.compiler.is_msvc();

        writeln!(out, "# Generated by ordo (test build)").unwrap();
        writeln!(out, "ninja_required_version = 1.3").unwrap();
        writeln!(out).unwrap();

        let c_exe = self.compiler.c_executable();
        let cpp_exe = self.compiler.cpp_executable();

        if msvc {
            writeln!(out, "rule cc").unwrap();
            writeln!(
                out,
                "  command = {c_exe} /nologo $flags /showIncludes /Fo$out $in"
            )
            .unwrap();
            writeln!(out, "  deps = msvc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();

            writeln!(out, "rule cxx").unwrap();
            writeln!(
                out,
                "  command = {cpp_exe} /nologo $flags /showIncludes /Fo$out $in"
            )
            .unwrap();
            writeln!(out, "  deps = msvc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();

            writeln!(out, "rule link").unwrap();
            writeln!(out, "  command = link.exe /nologo $flags $in /OUT:$out").unwrap();
            writeln!(out, "  description = Linking $out").unwrap();
            writeln!(out).unwrap();

            writeln!(out, "rule ar").unwrap();
            writeln!(out, "  command = lib.exe /nologo /OUT:$out $in").unwrap();
            writeln!(out, "  description = Archiving $out").unwrap();
            writeln!(out).unwrap();
        } else {
            writeln!(out, "rule cc").unwrap();
            writeln!(out, "  command = {c_exe} $flags -MD -MF $out.d -o $out $in").unwrap();
            writeln!(out, "  depfile = $out.d").unwrap();
            writeln!(out, "  deps = gcc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();

            writeln!(out, "rule cxx").unwrap();
            writeln!(
                out,
                "  command = {cpp_exe} $flags -MD -MF $out.d -o $out $in"
            )
            .unwrap();
            writeln!(out, "  depfile = $out.d").unwrap();
            writeln!(out, "  deps = gcc").unwrap();
            writeln!(out, "  description = Compiling $in").unwrap();
            writeln!(out).unwrap();

            let link_exe = if self.has_cpp() { cpp_exe } else { c_exe };
            writeln!(out, "rule link").unwrap();
            writeln!(out, "  command = {link_exe} $flags $in -o $out").unwrap();
            writeln!(out, "  description = Linking $out").unwrap();
            writeln!(out).unwrap();

            writeln!(out, "rule ar").unwrap();
            writeln!(out, "  command = ar rcs $out $in").unwrap();
            writeln!(out, "  description = Archiving $out").unwrap();
            writeln!(out).unwrap();
        }

        let obj_ext = if msvc { "obj" } else { "o" };

        // Build test library from non-main sources (for executable projects)
        let mut lib_object = None;
        if !self.lib_sources.is_empty()
            && let Some(ref lib_name) = self.lib_name
        {
            let mut lib_objects = Vec::new();
            for src in &self.lib_sources {
                let rel_src = self.rel(src);
                let stem = src.file_stem().unwrap_or_default().to_string_lossy();
                let obj = format!("lib_{stem}.{obj_ext}");
                let cpp = is_cpp_source(src);
                let compile_flags = self.compile_flags_str_for(cpp, &[]);
                let rule = if cpp { "cxx" } else { "cc" };

                writeln!(out, "build {obj}: {rule} {}", rel_src.display()).unwrap();
                writeln!(out, "  flags = {compile_flags}").unwrap();
                writeln!(out).unwrap();

                lib_objects.push(obj);
            }

            let lib_ext = if msvc { "lib" } else { "a" };
            let lib_prefix = if msvc { "" } else { "lib" };
            let lib_file = format!("{lib_prefix}{lib_name}.{lib_ext}");
            let objs = lib_objects.join(" ");
            writeln!(out, "build {lib_file}: ar {objs}").unwrap();
            writeln!(out).unwrap();

            lib_object = Some(lib_file);
        }

        let exe_ext = crate::compiler::executable_extension();

        // Build each test binary
        let output_dir = self.build_dir.parent().unwrap_or(Path::new("."));
        for test in &self.tests {
            let rel_src = self.rel(&test.test_source);
            let obj = format!("test_{}.{obj_ext}", test.name);
            let cpp = is_cpp_source(&test.test_source);
            let compile_flags = self.compile_flags_str_for(cpp, &test.framework_include_dirs);
            let rule = if cpp { "cxx" } else { "cc" };

            writeln!(out, "build {obj}: {rule} {}", rel_src.display()).unwrap();
            writeln!(out, "  flags = {compile_flags}").unwrap();
            writeln!(out).unwrap();

            let bin_path = output_dir.join(format!("{}{exe_ext}", test.name));
            let rel_bin = pathdiff::diff_paths(&bin_path, &self.build_dir)
                .unwrap_or_else(|| bin_path.clone());

            let mut link_inputs = vec![obj];

            if let Some(ref lib_file) = lib_object {
                link_inputs.push(lib_file.clone());
            }
            if let Some(ref project_lib) = self.project_lib_path {
                let rel_lib = self.rel(project_lib);
                link_inputs.push(rel_lib.display().to_string());
            }

            let inputs = link_inputs.join(" ");
            let lflags = self.link_flags_str(&test.framework_lib_dirs, &test.framework_libs);

            writeln!(out, "build {}: link {inputs}", rel_bin.display()).unwrap();
            if !lflags.is_empty() {
                writeln!(out, "  flags = {lflags}").unwrap();
            }
            writeln!(out).unwrap();

            test_binaries.push((test.name.clone(), bin_path));
        }

        if !test_binaries.is_empty() {
            let defaults: Vec<String> = test_binaries
                .iter()
                .map(|(_, p)| {
                    let rel = pathdiff::diff_paths(p, &self.build_dir).unwrap_or_else(|| p.clone());
                    rel.display().to_string()
                })
                .collect();
            writeln!(out, "default {}", defaults.join(" ")).unwrap();
        }

        TestNinjaOutput {
            build_ninja: out,
            test_binaries,
        }
    }

    fn has_cpp(&self) -> bool {
        self.lib_sources.iter().any(|s| is_cpp_source(s))
            || self.tests.iter().any(|t| is_cpp_source(&t.test_source))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::clang::ClangCompiler;

    fn basic_generator(package_type: PackageType) -> NinjaOutput {
        let compiler = ClangCompiler;
        let sources = vec![PathBuf::from("src/main.cpp")];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            PathBuf::from("."),
            "myapp".to_string(),
            package_type,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        generator.generate()
    }

    #[test]
    fn ninja_has_required_version() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("ninja_required_version"));
    }

    #[test]
    fn ninja_has_compile_rule() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("rule cc"));
        assert!(output.build_ninja.contains("depfile"));
    }

    #[test]
    fn ninja_executable_has_link_rule() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("rule link"));
        assert!(output.build_ninja.contains("myapp"));
    }

    #[test]
    fn ninja_static_library_has_ar_rule() {
        let output = basic_generator(PackageType::StaticLibrary);
        assert!(output.build_ninja.contains("rule ar"));
        assert!(output.build_ninja.contains("libmyapp.a"));
    }

    #[test]
    fn ninja_shared_library_has_shared_flag() {
        let output = basic_generator(PackageType::SharedLibrary);
        assert!(output.build_ninja.contains("-shared"));
        let ext = crate::compiler::shared_lib_extension();
        assert!(output.build_ninja.contains(&format!("libmyapp{ext}")));
    }

    #[test]
    fn ninja_has_default_target() {
        let output = basic_generator(PackageType::Executable);
        assert!(output.build_ninja.contains("default"));
        assert!(output.build_ninja.contains("myapp"));
    }

    #[test]
    fn ninja_multiple_sources() {
        let compiler = ClangCompiler;
        let sources = vec![PathBuf::from("src/main.cpp"), PathBuf::from("src/util.cpp")];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            PathBuf::from("."),
            "myapp".to_string(),
            PackageType::Executable,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        let output = generator.generate();

        assert!(output.build_ninja.contains("build main.o: cxx"));
        assert!(output.build_ninja.contains("build util.o: cxx"));
    }

    #[test]
    fn compile_commands_is_valid_json() {
        let output = basic_generator(PackageType::Executable);
        let parsed: Vec<serde_json::Value> =
            serde_json::from_str(&output.compile_commands).unwrap();
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0]["file"], "src/main.cpp");
        assert!(parsed[0]["arguments"].as_array().unwrap().len() > 1);
    }

    #[test]
    fn compile_commands_multiple_sources() {
        let compiler = ClangCompiler;
        let sources = vec![PathBuf::from("src/main.cpp"), PathBuf::from("src/util.cpp")];
        let generator = NinjaGenerator::new(
            &compiler,
            sources,
            PathBuf::from("target/debug/build"),
            PathBuf::from("."),
            "myapp".to_string(),
            PackageType::Executable,
            CompileFlags::default(),
            LinkFlags::default(),
        );
        let output = generator.generate();

        let parsed: Vec<serde_json::Value> =
            serde_json::from_str(&output.compile_commands).unwrap();
        assert_eq!(parsed.len(), 2);
    }

    #[test]
    fn compile_commands_includes_system_paths() {
        let output = basic_generator(PackageType::Executable);
        let parsed: Vec<serde_json::Value> =
            serde_json::from_str(&output.compile_commands).unwrap();
        let args = parsed[0]["arguments"].as_array().unwrap();
        let has_isystem = args.iter().any(|a| a.as_str() == Some("-isystem"));
        // On any system with clang++ we should have system includes
        if crate::backend::compiler::which_exe("clang++").is_some() {
            assert!(
                has_isystem,
                "compile_commands.json should contain -isystem flags"
            );
        }
    }
}
