#![allow(dead_code)]

use crate::core::manifest::DependencySource;
use crate::core::resolver::ResolvedPackage;
use miette::{IntoDiagnostic, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

const LOCK_VERSION: u32 = 1;

#[derive(Debug, Serialize, Deserialize)]
pub struct LockFile {
    pub version: u32,
    #[serde(rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
}

impl LockFile {
    pub fn new(resolved: &[ResolvedPackage]) -> Self {
        let packages = resolved
            .iter()
            .map(|pkg| LockedPackage {
                name: pkg.name.clone(),
                version: pkg.version.to_string(),
                source: source_to_string(&pkg.source),
                checksum: None,
            })
            .collect();

        Self {
            version: LOCK_VERSION,
            packages,
        }
    }

    pub fn load(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path).into_diagnostic()?;
        toml::from_str(&content).into_diagnostic()
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let header = "# Auto-generated by Ordo. Do not edit manually.\n\n";
        let content = toml::to_string_pretty(self).into_diagnostic()?;
        std::fs::write(path, format!("{header}{content}")).into_diagnostic()
    }

    pub fn is_fresh(&self, resolved: &[ResolvedPackage]) -> bool {
        let locked: BTreeMap<&str, &LockedPackage> =
            self.packages.iter().map(|p| (p.name.as_str(), p)).collect();

        for pkg in resolved {
            let source_str = source_to_string(&pkg.source);
            match locked.get(pkg.name.as_str()) {
                Some(existing) => {
                    let is_stub = pkg.version == semver::Version::new(0, 0, 0);
                    let version_matches = is_stub || existing.version == pkg.version.to_string();
                    if !version_matches || existing.source != source_str {
                        return false;
                    }
                }
                None => return false,
            }
        }

        true
    }

    pub fn merge(&mut self, resolved: &[ResolvedPackage]) {
        let new_lock = Self::new(resolved);
        for pkg in new_lock.packages {
            if let Some(pos) = self.packages.iter().position(|p| p.name == pkg.name) {
                self.packages[pos] = pkg;
            } else {
                self.packages.push(pkg);
            }
        }
        self.packages.sort_by(|a, b| a.name.cmp(&b.name));
    }

    pub fn verify_checksums(&self) -> Result<()> {
        for pkg in &self.packages {
            if let Some(ref checksum) = pkg.checksum {
                tracing::debug!("verified checksum for {}: {}", pkg.name, checksum);
                // Actual verification happens during fetch — this is the framework
            }
        }
        Ok(())
    }
}

fn source_to_string(source: &DependencySource) -> String {
    match source {
        DependencySource::Path => "path".to_string(),
        DependencySource::Git => "git".to_string(),
        DependencySource::Registry => "registry".to_string(),
        DependencySource::Provider(p) => p.to_string(),
        DependencySource::Workspace => "workspace".to_string(),
        DependencySource::Unknown => "unknown".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::manifest::DependencySource;
    use crate::core::resolver::ResolvedPackage;
    use semver::Version;
    use tempfile::TempDir;

    fn sample_resolved() -> Vec<ResolvedPackage> {
        vec![
            ResolvedPackage {
                name: "fmt".to_string(),
                version: Version::new(11, 0, 0),
                source: DependencySource::Registry,
            },
            ResolvedPackage {
                name: "core".to_string(),
                version: Version::new(0, 1, 0),
                source: DependencySource::Path,
            },
        ]
    }

    #[test]
    fn new_creates_correct_packages() {
        let lock = LockFile::new(&sample_resolved());
        assert_eq!(lock.version, 1);
        assert_eq!(lock.packages.len(), 2);
        assert_eq!(lock.packages[0].name, "fmt");
        assert_eq!(lock.packages[0].version, "11.0.0");
        assert_eq!(lock.packages[0].source, "registry");
        assert_eq!(lock.packages[1].source, "path");
    }

    #[test]
    fn round_trip_save_load() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("Ordo.lock");

        let lock = LockFile::new(&sample_resolved());
        lock.save(&path).unwrap();

        let loaded = LockFile::load(&path).unwrap();
        assert_eq!(loaded.version, 1);
        assert_eq!(loaded.packages.len(), 2);
        assert_eq!(loaded.packages[0].name, lock.packages[0].name);
        assert_eq!(loaded.packages[0].version, lock.packages[0].version);
    }

    #[test]
    fn is_fresh_when_matching() {
        let resolved = sample_resolved();
        let lock = LockFile::new(&resolved);
        assert!(lock.is_fresh(&resolved));
    }

    #[test]
    fn is_stale_when_version_changed() {
        let resolved = sample_resolved();
        let lock = LockFile::new(&resolved);

        let mut updated = sample_resolved();
        updated[0].version = Version::new(12, 0, 0);
        assert!(!lock.is_fresh(&updated));
    }

    #[test]
    fn is_stale_when_dep_added() {
        let resolved = sample_resolved();
        let lock = LockFile::new(&resolved);

        let mut updated = sample_resolved();
        updated.push(ResolvedPackage {
            name: "spdlog".to_string(),
            version: Version::new(1, 14, 0),
            source: DependencySource::Registry,
        });
        assert!(!lock.is_fresh(&updated));
    }

    #[test]
    fn is_fresh_when_subset() {
        let resolved = sample_resolved();
        let lock = LockFile::new(&resolved);

        let subset = vec![sample_resolved().remove(0)];
        assert!(lock.is_fresh(&subset));
    }

    #[test]
    fn saved_file_has_header() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("Ordo.lock");

        let lock = LockFile::new(&sample_resolved());
        lock.save(&path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("# Auto-generated by Ordo"));
    }

    #[test]
    fn source_format_strings() {
        assert_eq!(source_to_string(&DependencySource::Path), "path");
        assert_eq!(source_to_string(&DependencySource::Git), "git");
        assert_eq!(source_to_string(&DependencySource::Registry), "registry");
        assert_eq!(source_to_string(&DependencySource::Workspace), "workspace");
    }
}
